version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: node:alpine
    working_dir: /usr/src/app
    networks: 
      - appnet
    volumes: 
      - ./application:/usr/src/app
    command: npm start  
  mongo:
    image: mongo:latest
    volumes:
      - dbdata:/data
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local